### ISSUE TITLE
pino: option to disable the extension

### ISSUE THREAD

**Issue by danielbayerlein** [newrelic/newrelic-node-log-extensions#66]
It would be great if there was an option to disable the extension. During local development I do not want to use the extension.

**Comment by jordigh** [comment]
Hi!

What kind of solution did you have in mind? For local development, you probably don't want to enable the New Relic agent either, and if you disable that from the `newrelic.js` config as [detailed here](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#agent-enabled), then log enriching with Pino will also be disabled.

Alternatively, you can also write your own code to look something like this

```
const enricher = process.env.NODE_ENV === 'development' ? function() {} : pino_enricher
```

If these two don't work for you, what would you like to have instead?

**Comment by jordigh** [comment]
I'll assume the above suggestions solved the problem. If they haven't, we can reopen the issue.
