### ISSUE TITLE
NewRelic Pino Enricher not working with Pino 2nd arg constructor

### ISSUE THREAD

**Issue by rbrooksAvetta** [newrelic/newrelic-node-log-extensions#93]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

In the use case in which the Pino logger must be constructed with options, I.e. a  transport, there is no way to initialize the NRPino enricher. It does not work as the second argument in the Pino 2 argument constructor.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Ignores the function formatter provided by nrPino() call
```
let logger = pino({
  transport: {
    pipeline: [{
      target: './pino-log-level.transport-v2.js'
    }, {
      target: 'pino/file'
    }],
  }
}, nrPino())
```
Throws exception 
```
let logger = pino({useLevelLabels: true}, nrPino())


TypeError: stream.write is not a function
    at Pino.write (/Users/robert.brooks/development/ruleengine/node_modules/pino/lib/proto.js:210:10)
    at Pino.LOG [as info] (/Users/robert.brooks/development/ruleengine/node_modules/pino/lib/tools.js:57:21)
    at file:///Users/robert.brooks/development/ruleengine/lib/index.js:110:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Process finished with exit code 1

```
[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

I expect Pino enrichment to work with any options set for the Pino logger construction
```
let logger = pino({
  transport: {
    pipeline: [{
      target: './pino-log-level.transport-v2.js'
    }, {
      target: 'pino/file'
    }],
  }
}, nrPino())
```

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

```
let logger = pino({useLevelLabels: true}, nrPino())


TypeError: stream.write is not a function
    at Pino.write (/Users/robert.brooks/development/ruleengine/node_modules/pino/lib/proto.js:210:10)
    at Pino.LOG [as info] (/Users/robert.brooks/development/ruleengine/node_modules/pino/lib/tools.js:57:21)
    at file:///Users/robert.brooks/development/ruleengine/lib/index.js:110:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Process finished with exit code 1

```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jmartin4563** [comment]
Hiya @rbrooksAvetta! The function exported by the Pino Log Enricher isn't a `destination` as described by the [docs](https://github.com/pinojs/pino/blob/master/docs/api.md#export), which is why you're getting an error.

I'm curious if you've tried just using the auto-instrumentation that comes with the agent; that doesn't require you pass anything to the pino instantiation call. I put together a little [example](https://glitch.com/edit/#!/hickory-pyrite-cloudberry?path=server.js) using both of the instantiation methods you described, and am able to see the logs in the UI.

If you did try the auto-instrumentation, and it wasn't working for you, I'd love to get more info about what specifically wasn't working.

**Comment by bizob2828** [comment]
Also @rbrooksAvetta have you tried doing this?

```js
let logger = pino({
  ...nrPino(),
  transport: {
    pipeline: [{
      target: './pino-log-level.transport-v2.js'
    }, {
      target: 'pino/file'
    }],
  }
})
```

I would still heed the advice of @jmartin4563 and just rely on the agent to instrument pino for you.  These log enrichers are essentially deprecated in favor of in agent log forwarding

**Comment by bizob2828** [comment]
@rbrooksAvetta I'm going to close this as this was just a misunderstanding of what this package is and how to integrate into your existing pino instance.  I want to stress again that you should just rely on the new relic node.js agent to auto instrument pino and forward logs for you.

**Comment by rbrooksAvetta** [comment]
Sorry, I am so late on this task. Yes I have tried using the transporter without the instantiating the enricher but I do not see attributes that should be included in the logs, I.e entity.name, entity.guuid, hostname. When I run locally with the node-agent and local-decorating setup. I actually thought this was needed for local-decoration but it is good to know that it should not be.

**Comment by bizob2828** [comment]
@rbrooksAvetta can you provide steps to reproduce?  the `entity.name`, `entity.guid` and `hostname` should always be present if the agent is connected.
